Add multiline messages and messages from file
flavorjones/irc-notification-resource pull request #16
Opened 2020-01-14 17:33 UTC by avanier

This PR adds the following:

- The ability to take a message from a file or from the `param`.
- The ability to send multiline messages as a sequence of messages
- Adds some safety features to the integration test script
- Version pins Alpine in the Dockefile
- Cleans the image on build to expand compatibility to OCI image builders that don't respect `.dockerignore`

2020-01-15 14:57 UTC, flavorjones commented
Thanks for submitting this! I'm going to make some comments on the commits.

2020-01-15 14:58 UTC, flavorjones requested changes
Can I ask that commit 1ea78e47489eb00f5cd0fd5aca327cdd8724d770 go into a separate PR? I'd like to understand more deeply the problem you're solving, and this seems unrelated to the feature/functional parts of the PR.

2020-01-15 15:00 UTC, flavorjones commented on pkg/irc/irc.go
> +const VERSION = "v1.3.0"
I'd prefer if the version wasn't bumped in a PR - can I ask that you please remove this line?

2020-01-15 15:20 UTC, avanier commented
> Can I ask that commit [1ea78e4](https://github.com/flavorjones/irc-notification-resource/commit/1ea78e47489eb00f5cd0fd5aca327cdd8724d770) go into a separate PR? I'd like to understand more deeply the problem you're solving, and this seems unrelated to the feature/functional parts of the PR.

The situation I was facing is I discovered that `podman` and `buildah` would ignore the the `.dockerignore` and stick my locally built artifacts in the build context and `make test` would fail with `file not found` due to dynamic linking errors.

As for the pinning of the image versions, it _"fixes nothing"_ I was on a drive-by fix binge and it went in.

2020-01-15 21:28 UTC, avanier commented
The Docker image commit has been moved to #17 .

2020-03-15 03:24 UTC, avanier commented
Bump

2020-03-18 12:44 UTC, flavorjones commented
@avanier Thanks for your patience. It's been hard to make time for open-source work lately. I'll schedule some time to work on this in the next few days.

2020-08-14 19:55 UTC, flavorjones commented
I've added some test coverage and some other small changes, and merged this manually. Thank you for your contribution! I'll update the CHANGELOG to credit you and ship an update now.

2020-08-14 20:01 UTC, merged

2020-08-14 20:32 UTC, flavorjones commented
v1.3.0 has been shipped with these features. Thanks again!